### ISSUE TITLE
Username or Email as Unique

### ISSUE THREAD

**Issue by StevenWeathers** [Toddish/Verify#14]
It seems neither the Username or Email columns are unique, this can cause two accounts of the same username or email to be created.  Not sure if this was intentional but I would suggest at least one or both of these fields be required to be unique.

**Comment by Toddish** [comment]
Because the user can choose what fields a user can log in by, we can't set which field is unique on migration, as then we lose some of the flexibility.

I'll add in a comment in the installation instructions though about going in and setting one (or both) as unique depending on the project needs.

Thanks for the suggestion!
